# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-14 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_entering'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entering',
        ),
    ]
